name: Auto Push

on:
  push:
    branches:
      - main

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Henokmekonnen1234'
          git config --global user.email 'henokmac2425@gmail.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "Automated commit"
          git push origin main
